---
name: buildstack

releases:
- name: buildstack
  version: latest

stemcells:
- alias: default
  os: ubuntu-trusty
  version: "3468.21"

update:
  canaries: 1
  max_in_flight: 1
  canary_watch_time: 15000-300000
  update_watch_time: 15000-300000

instance_groups:
- name: jenkins-master
  azs:
  - z1
  instances: 1
  jobs:
  - name: jenkins-master
    release: buildstack
    properties: 
      jenkins:
        server:
          address: "http://localhost:8080/"
        admin:
          email: "admin@localhost"
          password: ((jenkins_admin_password))
        agent:
          password: ((jenkins_agent_password))
  vm_type: default
  vm_extensions: [internet-required, jenkins-pool]
  persistent_disk_pool: 100GB
  stemcell: default
  networks:
  - name: default
- name: jenkins-slave
  azs:
  - z1
  - z2
  instances: 2
  jobs:
  - name: jenkins-slave
    release: buildstack
    properties: 
      jenkins:
        slave:
          master_password: ((jenkins_agent_password))
          master_username: agent
          executors: 2
          mode: exclusive
          labels: "build"    
      nexus:
        admin:
          username: admin
          password: ((nexus_admin_password))
        deployer:
          username: jenkins
          password: ((nexus_deployer_password))
  vm_type: default
  stemcell: default
  networks:
  - name: default
- name: nexus
  azs:
  - z1
  instances: 1
  jobs:
  - name: nexus
    release: buildstack
    properties:
      nexus:
        admin:
          password: ((nexus_admin_password))
        deployer:
          password: ((nexus_deployer_password))
  vm_type: default
  stemcell: default
  networks:
  - name: default
- name: sonarqube
  azs:
  - z1
  instances: 1
  jobs:
  - name: sonarqube
    release: buildstack
    properties:
      sonar:
        mysql:
          username: ((sonar_mysql_username))
          password: ((sonar_mysql_password))
          host: localhost
        server:
          port: ((sonar_server_port))
          address: ((sonar_server_address))
  - name: cloud-sql-proxy
    release: buildstack
    properties:
      proxy:
        instance: ((cloudsql.proxy.instance_name))
        port: 3306
        auth: ((cloudsql.proxy.auth))
  vm_type: default
  vm_extensions: [internet-required]
  stemcell: default
  networks:
  - name: default
- name: gerrit
  azs:
  - z1
  instances: 1
  jobs:
  - name: gerrit
    release: buildstack
    properties:
      gerrit:
        mysql:
          password: ((gerrit_mysql_password))
          host: localhost
  - name: cloud-sql-proxy
    release: buildstack
    properties:
      proxy:
        instance: ((cloudsql.proxy.instance_name))
        port: 3306
        auth: ((cloudsql.proxy.auth))
  vm_type: default
  vm_extensions: [internet-required]
  persistent_disk_pool: 100GB
  stemcell: default
  networks:
  - name: default

variables:
- name: jenkins_admin_password
  type: password
- name: jenkins_agent_password
  type: password
- name: nexus_admin_password
  type: password
- name: nexus_deployer_password
  type: password
- name: sonar_mysql_password
  type: password
- name: gerrit_mysql_password
  type: password
