instance_groups:
- azs:
  - z1
  instances: 1
  jobs:
  - name: jenkins-master
    properties:
      jenkins:
        admin:
          email: admin@localhost
          password: ((jenkins_admin_password))
        agent:
          password: ((jenkins_agent_password))
        server:
          address: http://localhost:8080/
    release: devtools
  name: jenkins-master
  networks:
  - name: default
  persistent_disk_pool: 100GB
  stemcell: default
  vm_extensions:
  - internet-required
  - jenkins-pool
  vm_type: default
- azs:
  - z1
  - z2
  instances: 2
  jobs:
  - name: jenkins-slave
    properties:
      jenkins:
        slave:
          executors: 2
          labels: build
          master_password: ((jenkins_agent_password))
          master_username: agent
          mode: exclusive
      nexus:
        admin:
          password: ((nexus_admin_password))
          username: admin
        deployer:
          password: ((nexus_deployer_password))
          username: jenkins
    release: devtools
  name: jenkins-slave
  networks:
  - name: default
  stemcell: default
  vm_type: default
- azs:
  - z1
  instances: 1
  jobs:
  - name: nexus
    properties:
      nexus:
        admin:
          password: ((nexus_admin_password))
        deployer:
          password: ((nexus_deployer_password))
    release: devtools
  name: nexus
  networks:
  - name: default
  stemcell: default
  vm_type: default
- azs:
  - z1
  instances: 1
  jobs:
  - name: sonarqube
    properties:
      sonar:
        mysql:
          host: ((buildstack_db_instance_ip))
          password: ((sonar_mysql_password))
          username: ((sonar_mysql_username))
        server:
          address: ((sonar_server_address))
          port: ((sonar_server_port))
    release: devtools
  name: sonarqube
  networks:
  - name: default
  stemcell: default
  vm_extensions:
  - internet-required
  vm_type: default
- azs:
  - z1
  instances: 1
  jobs:
  - name: gerrit
    properties:
      gerrit:
        mysql:
          host: ((buildstack_db_instance_ip))
          password: ((gerrit_mysql_password))
    release: devtools
  name: gerrit
  networks:
  - name: default
  persistent_disk_pool: 100GB
  stemcell: default
  vm_extensions:
  - internet-required
  vm_type: default
- name: uaa
  azs:
  - z1
  instances: 1
  vm_type: default
  vm_extensions:
  - internet-required
  persistent_disk_type: 10GB
  stemcell: default
  networks:
  - name: default
  jobs:
  - name: uaa
    release: uaa
    properties:
      login:
        saml:
          serviceProviderKey: "((uaa_login_saml.private_key))"
          serviceProviderCertificate: "((uaa_login_saml.certificate))"
      uaa:
        clients:
          admin:
            authorized-grant-types: client_credentials
            scope: uaa.none
            authorities: uaa.admin,clients.read,clients.write,clients.secret,scim.read,scim.write,clients.admin
            secret: "((uaa_admin_client_secret))"
        jwt:
          policy:
            active_key_id: key-1
            keys:
              key-1:
                signingKey: "((uaa_jwt_signing_key.private_key))"
        scim:
          user:
            override: true
          users:
            - name: admin
              password: "((uaa_admin_password))"
              groups:
                - uaa.admin
            - name: marissa
              password: koala
              groups:
                - uaa.user
        sslCertificate: "((uaa_ssl.certificate))"
        sslPrivateKey: "((uaa_ssl.private_key))"
        url: https://uaa.((system_domain))
      uaadb:
        address: 127.0.0.1
        databases:
        - name: uaadb
          tag: uaa
        db_scheme: postgresql
        port: 5524
        roles:
        - name: uaaadmin
          password: admin
          tag: admin
  - name: uaa_postgres
    release: uaa
    properties:
      postgres:
        address: 127.0.0.1
        port: 5524
        roles:
          - tag: admin
            name: uaaadmin
            password: admin
        databases:
          - tag: uaa
            name: uaadb
            citext: true
name: buildstack
releases:
- name: uaa
  sha1: 462383bd04d75ba5a0fd5e205853719b5b78423d
  url: https://bosh.io/d/github.com/cloudfoundry/uaa-release?v=56
  version: 56
- name: devtools
  sha1: c72453f04143a35da7926b29fb913798a8a4b616
  url: https://storage.googleapis.com/finkit-buildstack-releases/releases/devtools-boshrelease-0.0.1.tgz
  version: 0.0.1
stemcells:
- alias: default
  os: ubuntu-trusty
  version: "3541.9"
update:
  canaries: 1
  canary_watch_time: 15000-300000
  max_in_flight: 1
  update_watch_time: 15000-300000
variables:
- name: jenkins_admin_password
  type: password
- name: jenkins_agent_password
  type: password
- name: nexus_admin_password
  type: password
- name: nexus_deployer_password
  type: password
- name: sonar_mysql_password
  type: password
- name: gerrit_mysql_password
  type: password
- name: uaa_ca
  type: certificate
  options:
    is_ca: true
    common_name: uaaCA
- name: uaa_ssl
  type: certificate
  options:
    ca: uaa_ca
    common_name: uaa.service.cf.internal
    alternative_names:
    - uaa.service.cf.internal
- name: uaa_login_saml
  type: certificate
  options:
    ca: uaa_ca
    common_name: uaa_login_saml
- name: uaa_admin_client_secret
  type: password
- name: uaa_admin_password
  type: password
- name: uaa_jwt_signing_key
  type: rsa
