
---
name: gerrit

releases:
- name: buildstack
  version: latest

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

update:
  canaries: 1
  canary_watch_time: 10000-600000
  update_watch_time: 10000-600000
  max_in_flight: 1
  serial: true

instance_groups:
- name: gerrit
  azs:
  - z1
  instances: 1
  jobs:
  - name: gerrit
    release: buildstack
    properties:
      gerrit:
        mysql:
          password: ((gerrit_mysql_password))
          host: localhost
  - name: cloud-sql-proxy
    release: buildstack
    properties:
      proxy:
        instance: ((cloudsql.proxy.instance_name))
        port: 3306
        auth: ((cloudsql.proxy.auth))
  vm_type: m3.medium
  persistent_disk_pool: 100GB
  stemcell: default
  networks:
  - name: buildstack

variables:
- name: gerrit_mysql_password
  type: password

tags:
  project: gerrit
