---
name: nexus

releases:
- name: buildstack
  version: latest

stemcells:
- alias: default
  os: ubuntu-trusty
  version: "3468.21"

update:
  canaries: 1
  max_in_flight: 1
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000

instance_groups:
- name: nexus
  azs:
  - z1
  instances: 1
  jobs:
  - name: nexus
    release: buildstack
    properties:
      nexus:
        admin:
          password: ((nexus_admin_password))
  vm_type: default
  stemcell: default
  networks:
  - name: default

variables:
- name: nexus_admin_password
  type: password
